<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Enviar</name>
   <tag></tag>
   <elementGuidId>ed81d733-ab51-4dc5-af12-befe4033fe08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='sendBtn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sendBtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4ff3edf9-7196-4563-9795-71ae0a6d2b63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Enviar</value>
      <webElementGuid>93cecf8f-7770-4e86-abee-e9d990824af8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6df05f50-60bc-4142-8ecd-906a55b892f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sendBtn</value>
      <webElementGuid>8e686b40-0aae-44a2-9902-70a8b3a13080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button large blue btn btn-accentprimary explanation</value>
      <webElementGuid>5d91229f-a198-43c7-b1a1-b5d0cb794e12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-title</name>
      <type>Main</type>
      <value>Enviar</value>
      <webElementGuid>dc698f86-e9db-496b-aedb-63af76c25ebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip116648</value>
      <webElementGuid>2c9019e9-61ae-43fa-b9ea-273a07bbcb22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enviar</value>
      <webElementGuid>2440f777-97e7-464b-88e1-501734970858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sendBtn&quot;)</value>
      <webElementGuid>8b3d00cc-1992-4fc7-93fc-d0e4365fbfe6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='sendBtn']</value>
      <webElementGuid>f9783932-214a-44a5-8fef-5141b721c9f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filemailuploadercontainer']/div/button[4]</value>
      <webElementGuid>225d8f66-8074-4eed-b490-e1d6b8895632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[1]/following::button[1]</value>
      <webElementGuid>d551d8cb-65ab-461c-9297-65f15212c035</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reasumir'])[1]/following::button[2]</value>
      <webElementGuid>0c1c5ea6-50c8-4cc9-a96c-7460bb1a7153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[4]</value>
      <webElementGuid>43442289-74a9-49b7-8045-2f19c7ac2dc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'Enviar' and @type = 'button' and @id = 'sendBtn' and (text() = 'Enviar' or . = 'Enviar')]</value>
      <webElementGuid>0b4f907d-b7ee-4dd5-86cc-b402cd660131</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
