<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Transferencia en curso_ui-widget-content</name>
   <tag></tag>
   <elementGuidId>a1a742f2-7349-47e3-9dec-51fcf83a9d4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.ui-widget-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2e5a9732-f39c-493e-a19b-17a96238a589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Para (correo electrónico)</value>
      <webElementGuid>9c0a989b-0d34-44a8-8a12-19724e57ca1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>79e0995e-38e4-4539-8992-32c086b3fbdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Para (correo electrónico)</value>
      <webElementGuid>9ec7ac7f-69f1-4abe-8ee5-6f1e8e854b8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-widget-content</value>
      <webElementGuid>3cc43369-8c02-4bb2-ba77-8a836a259fa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divFilemailTo&quot;)/ul[@class=&quot;tagit ui-widget ui-widget-content ui-corner-all&quot;]/li[@class=&quot;tagit-new&quot;]/input[@class=&quot;ui-widget-content&quot;]</value>
      <webElementGuid>25ac4e49-5cf9-4dd7-a281-675181f5ce21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[2]</value>
      <webElementGuid>711ca75b-388a-4957-acaf-1b6b8c433a60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divFilemailTo']/ul/li/input</value>
      <webElementGuid>05566051-09f5-4ad6-bcd2-117cc392406d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>b2560f2b-330e-446a-b434-80f5e13bb078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Para (correo electrónico)' and @type = 'text']</value>
      <webElementGuid>cf3aae6a-5d69-4a7b-853a-449b82238f66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
