<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Transferencia en curso_FilemailFrom</name>
   <tag></tag>
   <elementGuidId>e03da157-37f0-4d96-b4e7-4bc23c304e0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FilemailFrom']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FilemailFrom</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2fd8c2f6-7688-4004-9545-66540de878ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>76060730-4bc0-4246-8634-e03cbb5099a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>De (correo electrónico)</value>
      <webElementGuid>6b9b3ee0-e0f8-456a-bc2a-3a5850691a6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-filemail-fieldkey</name>
      <type>Main</type>
      <value>From</value>
      <webElementGuid>459f6f58-3b46-47be-a43a-aa106e7667f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FilemailFrom</value>
      <webElementGuid>c4f58431-4f20-4f32-918a-fe9ffa275731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>main-textfield form-control</value>
      <webElementGuid>fa39c4ea-6fb2-496f-a84f-368afeb68b32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>De (correo electrónico)</value>
      <webElementGuid>c195823c-199c-4523-8b9d-2b3adf42d5bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>5d69208d-baad-40dc-89d1-2dde0122f63a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FilemailFrom&quot;)</value>
      <webElementGuid>f296d1d3-13b2-4c99-9547-8a3e01e2c9ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FilemailFrom']</value>
      <webElementGuid>ecadeec2-6619-4cc4-ad25-a31873e471cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divFilemailFrom']/input</value>
      <webElementGuid>4b660697-c411-4dba-9413-ed9a33a5beae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/input</value>
      <webElementGuid>c709277a-b0b8-4835-bb13-b14551523817</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'FilemailFrom' and @placeholder = 'De (correo electrónico)']</value>
      <webElementGuid>de3e38c9-54f7-45ee-b1e2-b8c37039bb05</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
