<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_juancmouhapegmail.com_FilemailSubject</name>
   <tag></tag>
   <elementGuidId>f57ce441-313b-4af1-9fa2-038dd1f703b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FilemailSubject']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FilemailSubject</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>581fd973-45ae-4beb-b3ae-ba0290ceb7a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e28bd2f6-96b2-4e0d-ac88-bd4e1626c4ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Asunto</value>
      <webElementGuid>77a8518c-27b4-4e2b-8f44-02ad8ec91c95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-filemail-fieldkey</name>
      <type>Main</type>
      <value>Subject</value>
      <webElementGuid>e97b0a15-2e12-405b-8663-2c8ba754c2c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FilemailSubject</value>
      <webElementGuid>b15e460c-1a4e-44e3-aa93-89b30ef3a861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>main-textfield form-control required </value>
      <webElementGuid>b731d46f-896e-4945-816a-622240398655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Asunto</value>
      <webElementGuid>4aea0e7d-d04c-45b3-b922-a72fda630438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>d3af29b0-85cd-4499-812c-8b7ff748bd71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>ca1a1ce4-ef8d-4e3a-b9ac-a28978819673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FilemailSubject&quot;)</value>
      <webElementGuid>0b047269-f22e-419a-bd91-179af73741ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FilemailSubject']</value>
      <webElementGuid>01345152-d729-41ec-9638-681073358d79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divFilemailSubject']/input</value>
      <webElementGuid>b53916c0-0d29-45f7-85b5-112bd878154f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>1a94a984-de5f-480d-8db9-e83e1459debc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'FilemailSubject' and @placeholder = 'Asunto']</value>
      <webElementGuid>dc149fc0-3269-4813-8a5f-3e2ccf3fb92d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
