<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Aadir Archivos</name>
   <tag></tag>
   <elementGuidId>f9460e7d-305e-4309-a709-4e33348b693b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='addBtn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addBtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>493c7970-446b-4a1f-b714-36df573a660d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>1h1migvlv1ck6sks147jc7e1i3s1</value>
      <webElementGuid>d082d5b7-89d3-42cb-95a6-72b6154edcd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fup-picker-label button btn btn-primary</value>
      <webElementGuid>ca4dd204-01a6-458d-8e1b-6677f58ab3c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addBtn</value>
      <webElementGuid>2ec51686-7b03-4279-9ab3-2f619c403fd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Añadir Archivos</value>
      <webElementGuid>0356184c-9dcb-45e6-9c99-510d873f01d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addBtn&quot;)</value>
      <webElementGuid>959e80a6-3ce5-46ce-9c73-5a31999d1e89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='addBtn']</value>
      <webElementGuid>1120b5ba-603d-4f79-a737-ac34c2aaa9e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filemailuploadercontainer']/div/label</value>
      <webElementGuid>fc0eaef4-e8d4-47ca-8140-6c9477650107</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preparando transferencia'])[1]/following::label[1]</value>
      <webElementGuid>67cc0fcd-bc15-4273-bd5e-d6e031491b3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='juancmouhape@gmail.com'])[1]/following::label[1]</value>
      <webElementGuid>9919931b-f0f6-439e-b160-7b8bde83413f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Añadir Carpeta'])[1]/preceding::label[1]</value>
      <webElementGuid>43c1de83-b372-463f-9049-8e357500e7d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>05bea9bf-4c37-415d-9bff-6c9bfad4c8d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'addBtn' and (text() = 'Añadir Archivos' or . = 'Añadir Archivos')]</value>
      <webElementGuid>8f81e77f-510b-4a59-8dbb-8cf99bb0ad83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
